repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python scripts/run_mypy.py
        language: system
        types: [python]
        pass_filenames: false
